[package]
name = "rax-core"
version = "0.1.0"
edition = "2021"

[dependencies]
object_store = "=0.7.0"
tokio = { version = "1", features = ["io-util", "sync", "macros", "rt"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bytes = "1"
