[package]
name = "rax-vector-search"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1"
hnsw_rs = "0.3.3"
embedvec = { version = "0.6.0", default-features = false }
serde_json = "1"
usearch = "2.24.0"
